[package]
name = "async-indexer"
version = "0.1.0"
authors = ["CS 538"]
edition = "2018"

[dependencies]
reqwest   = { version = "0.10.4", features = ["blocking"] }
tokio     = "0.2.17"
futures   = "0.3.4"
rss       = "1.9.0"
scraper   = "0.11.0"
url       = "2.1.1"
